
export interface ManifestoSection {
  id: string;
  title: string;
  content: string[];
}

export const SHORT_PLEDGE: string[] = [
  "I use AI as a thinking partner, never as a ghostwriter.",
  "I maintain 100% intellectual ownership of my findings.",
  "I disclose AI usage to my supervisor and within my thesis.",
  "I verify every citation generated by any system.",
  "I prioritize research rigor over convenience.",
  "I respect the historical norms of my academic discipline.",
  "I will not use AI to bypass human ethical reviews.",
  "My research contributes to human knowledge, not metrics.",
  "Moral responsibility for my findings lies solely with me.",
  "I honor the scholar's currency: original, rigorous thought."
];

export const MANIFESTO_SECTIONS: ManifestoSection[] = [
  {
    id: "transparency",
    title: "Transparency & Origin",
    content: [
      "ResearchGemini is built on the principle of Explicit Rationale. We avoid 'black-box' advisory systems that hide their logic.",
      "Scholars must understand why a suggestion was made, correlating it back to established academic frameworks and methodology standards.",
      "We visualize the 'thinking pipeline' so users can audit the AI's reasoning steps in real-time, preventing blind reliance on output.",
      "Every tool in the Research OS provides a clear 'Source of Logic' indicator to differentiate between data-driven and reasoning-driven advice.",
      "Advisory outputs are linked to recognized research handbooks to ensure compliance with global academic standards."
    ]
  },
  {
    id: "human-centric",
    title: "Human-in-the-Loop",
    content: [
      "The researcher is the Commanding Officer; ResearchGemini is the Intelligence Core. The system is hard-locked to prevent autonomous decision-making.",
      "Only human review boards can grant final ethical approval. Our system identifies risks, but never 'approves' research design.",
      "Interpretive Finality belongs to the scholar. The AI provides themes and patterns, but the human judgment draws the final conclusions.",
      "Methodological commitment must be justified by the scholar's voice. We provide the options; you provide the rationale.",
      "We encourage scholars to challenge AI suggestions as a part of their critical development process."
    ]
  },
  {
    id: "zero-ghostwriting",
    title: "Integrity Framework",
    content: [
      "ResearchGemini is prohibited from 'writing your thesis'. We provide skeletal structures, brainstorming frameworks, and critical critiques.",
      "If the system detects a request for verbatim generation of evaluative academic work, it defaults to an advisory-only state.",
      "Plagiarism-safe writing checklists are integrated into every drafting tool to reinforce individual accountability.",
      "Knowledge integrity is a non-negotiable protocol. Our algorithms are optimized for rigor, not for passing detection software.",
      "We actively educate scholars on the difference between 'co-thinking' and 'outsourcing' intellectual labor."
    ]
  },
  {
    id: "privacy",
    title: "Data & Privacy",
    content: [
      "Your research data is your private intellectual property. We employ end-to-end local encryption to protect nascent ideas.",
      "No research data submitted to this OS is used for training commercial large language models outside of this environment.",
      "Vulnerability metrics and stress-pulse data are handled with clinical-grade confidentiality to support scholar wellbeing safely.",
      "Local-first storage ensures that even if our servers are offline, your journey map and progress remain in your control.",
      "We provide clear export tools so you can move your research intelligence out of our system whenever you choose."
    ]
  }
];
